components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4
            thread_name: main-worker
        fs-task-processor:
            worker_threads: 2
            thread_name: fs-worker

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8081
                task_processor: main-task-processor
            listener-monitor:
                port: 9091
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        testsuite-support: {}

        dns-client:
            fs-task-processor: fs-task-processor

        mongo-db: {}

        cache: {}

        rate-limiter: {}

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-server-monitor:
            path: /metrics
            method: GET
            task_processor: main-task-processor

        metrics:
            path: /cache-rate-limiting-metrics
            method: GET
            task_processor: main-task-processor

        handler-create-user:
            path: /api/v1/users
            method: POST
            task_processor: main-task-processor

        handler-find-user-by-login:
            path: /api/v1/users/by-login
            method: GET
            task_processor: main-task-processor

        handler-search-users-by-name:
            path: /api/v1/users/search
            method: GET
            task_processor: main-task-processor

        handler-login:
            path: /api/v1/auth/login
            method: POST
            task_processor: main-task-processor
